### PR TITLE
Ver.1

### PR DESCRIPTION
**Pull request by WangChing0723**
I finished Ver.1 about the Jokes project.
Please review my code !

### CODE REVIEW

**Comment by chengchiehhung** [comment]
Please make your variable names better so that others can understand what you want to express easily.

**Review by chengchiehhung — CHANGES_REQUESTED** [review]
Please revise variables' naming, thx!

**Comment by WangChing0723** [comment]
I revised variables' naming with Ver.1.1
Please review my code !

**Comment by chengchiehhung** [comment]
Please raise a request again so that I can approve it, thank you.

**Review by chengchiehhung — CHANGES_REQUESTED** [review]
Please modularize the part of with open(), it seems a little bit repetitive.

**Comment by WangChing0723** [comment]
I finished modularize the part of with open(), Please check it!

**Review by chengchiehhung — APPROVED** [review]
ok

**Pull request merged**
